name: Docker Compose CI

on:
  workflow_dispatch:

jobs:
  build-and-up:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Docker images
        run: docker compose pull

      - name: Start services with Docker Compose
        run: docker compose up -d

      - name: List running containers
        run: docker ps

      - name: Wait for services to initialize
        run: sleep 30

      - name: Copy dataset to client container
        run: docker cp ev_project/Electric_Vehicle_Population_Data.csv client:/home/hadoop/

      - name: Create HDFS directory
        run: docker exec client hdfs dfs -mkdir -p /data/ev

      - name: Upload dataset to HDFS
        run: docker exec client hdfs dfs -put -f /home/hadoop/Electric_Vehicle_Population_Data.csv /data/ev/

      - name: Run Spark Analysis
        run: |
          docker exec client bash -c "cd /home/hadoop/ev_project && spark-submit \
            --master yarn \
            --deploy-mode cluster \
            analiticas_ev.py"

      - name: Stop services
        if: always()
        run: docker compose down
